"""add processing_time and error_message to ocr_results

Revision ID: f2b705453c36
Revises: 8c84db4ab3f4
Create Date: 2026-04-02 19:09:09.218796
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f2b705453c36'
down_revision: Union[str, None] = '8c84db4ab3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
