"""add processing_time and error_message to ocr_results

Revision ID: f88f0c4add6c
Revises: f2b705453c36
Create Date: 2026-04-02 19:12:08.671593
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f88f0c4add6c'
down_revision: Union[str, None] = 'f2b705453c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
